name: conditional
on:
  workflow_dispatch:

jobs:
  read-file:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.name == "actionPlayground" }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print repo
        run: echo "${{ github.event.repository.name }}"
