name: HTTP Batch Playgroung

on:
  workflow_dispatch:

jobs:
  send-batch-http-request:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Deploy Stage
        uses: juancolchete/batch-http-request@main
        with:
          url: '${{ vars.URL_TEST }}'
          method: 'POST'
