name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello ${{ vars.MSG }}"
      - name: show api key
        run: echo "Api key:${{ secrets.API_KEY }}"
