name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print README
        run: cat README.md
